name: ci

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: read
      id-token: write
    env:
      MISE_HTTP_TIMEOUT: 120
      MISE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-macos
        with:
          install-fish: true
      - parallel:
          - run: make lint
          - run: make inspect-dependencies
      - run: make build-app
        env:
          XCODEBUILD_FLAGS: -showBuildTimingSummary
      - run: make test
